name: MemoZ CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test (Debug)
        run: swift test -v --configuration debug
      - name: Test (Release)
        run: swift test -v --configuration release -Xswiftc -enable-testing

  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test (Debug)
        uses: skiptools/swift-android-action@v2
        with:
          swift-configuration: debug
      - name: Test (Release)
        uses: skiptools/swift-android-action@v2
        with:
          swift-configuration: release

  watchOS:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4

      - run: |
            xcodebuild clean test \
              -configuration Release \
              -scheme "MemoZ" \
              -sdk "watchsimulator" \
              -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm" \
              ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO

  iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            xcodebuild clean test \
              -configuration Release \
              -scheme "MemoZ" \
              -sdk "iphonesimulator" \
              -destination "platform=iOS Simulator,name=iPhone 14" \
              ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO

  tvOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            xcodebuild clean test \
              -configuration Release \
              -scheme "MemoZ" \
              -sdk "appletvsimulator" \
              -destination "platform=tvOS Simulator,name=Apple TV" \
              ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO

  macOS12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Test (Debug)
        run: swift test -v --configuration debug
      - name: Test (Release)
        run: swift test -v --configuration release -Xswiftc -enable-testing
